-- 코드를 작성해주세요
WITH SUM_PRICE AS (
    SELECT 
        II.RARITY,
        II.PRICE
    FROM ITEM_INFO II
    WHERE II.RARITY = 'LEGEND'
)
SELECT SUM(PRICE) AS TOTAL_PRICE FROM SUM_PRICE

# SELECT 
#     II.RARITY,
#     II.PRICE
# FROM ITEM_INFO II
# WHERE II.RARITY = 'LEGEND'