SELECT 
    CC.CAR_ID,
    CC.CAR_TYPE,
    ROUND(30 * CC.DAILY_FEE * (1 - DP.DISCOUNT_RATE / 100), 0) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR CC
INNER JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP ON CC.CAR_TYPE = DP.CAR_TYPE
WHERE 
    (CC.CAR_TYPE = '세단' OR CC.CAR_TYPE = 'SUV')
    AND DP.DURATION_TYPE LIKE '30일%'
    AND CC.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30'
    )
    AND ROUND(30 * CC.DAILY_FEE * (1 - DP.DISCOUNT_RATE / 100), 0) BETWEEN 500000 AND 2000000
ORDER BY 
    FEE DESC, CC.CAR_TYPE ASC, CC.CAR_ID DESC;