-- 코드를 작성해주세요
WITH ECOLI_QUERY AS (
    SELECT 
    ID,
    SIZE_OF_COLONY,
    NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANK_QUERTILE
    FROM ECOLI_DATA
)
SELECT 
    ID, 
    CASE
        WHEN RANK_QUERTILE = 1 THEN 'CRITICAL'
        WHEN RANK_QUERTILE = 2 THEN 'HIGH'
        WHEN RANK_QUERTILE = 3 THEN 'MEDIUM'
        WHEN RANK_QUERTILE = 4 THEN 'LOW'
    END AS COLONY_NAME
FROM ECOLI_QUERY
ORDER BY ID
# SELECT ED.ID
# FROM ECOLI_DATA ED
# IF (ROUND()) AS COLONY_NAME

# ORDER BY SIZE_OF_COLONY DESC
-- 대장균 개체 크기 내림차순 정렬