-- 코드를 작성해주세요
# WITH COLONY_DISTRIBUTION AS (
#     ID,
#     SIZE_OF_COLONY,
#     IF ()
# )

SELECT 
    ID,
    CASE
        WHEN ED.SIZE_OF_COLONY <= 100 THEN 'LOW'
        WHEN ED.SIZE_OF_COLONY >= 100 AND ED.SIZE_OF_COLONY <= 1000 THEN 'MEDIUM'
        WHEN ED.SIZE_OF_COLONY > 1000 THEN 'HIGH'
        END AS SIZE
FROM ECOLI_DATA ED